### ISSUE TITLE
Members Index > Search

### ISSUE THREAD

**Issue by rodolfomartinez** [MikaSoftware/inthought#44]
**Summary:**
Right now the Search circle is just a static display. It should link to /members/member_search.html when clicked. It would be best if the entire circle (not just the icon) could be a clickable link

**Comment by bartmika** [comment]
![screen shot 2018-02-17 at 11 33 44 am](https://user-images.githubusercontent.com/5767602/36343148-8b3f3446-13d6-11e8-8b23-23404389a954.png)

I am looking at this form and I have a few concerns:

1. I want all forms not to have the same width, but limited width; more specifically, every field has a width specific to what you'd expect. For example first name and last name would probably be same, the phone field would be shorter so it can fit 10 digits.

2. I would like to have a mask to the telephone field so it's like (xxx) xxx-xxxx. Think of the Angle theme how it does it.

3. I would like to have validation to error if for example the first name field is larger then some character limit. The error message should be under field.

**Comment by bartmika** [comment]
Hi @KPSbuttar, I am having difficulty implementing your javascript code example. Unfortunately I am not as advanced as you are with jQuery. Here is the latest work I have done which works for basic form searching except the validation.

https://github.com/over55/overfiftyfive-django/blob/master/overfiftyfive/tenant_associate/templates/tenant_associate/associate_search.html

May I please get you to update the GUI and the javascript code to be more friendly on how to utilize? Here is what I would like done:

- Ensure your JavaScript code is **simple** and **easy to read**.

- Ensure your JavaScript code generates the proper errors and updates the GUI

- Ensure when user enters either basic or advanced search fields that they will be redirected to a URL. Please make a note in capital letters. I will look at your code and update it so it will generate the URL which will work with our system.

- Please email me if you have any difficulties understanding or need clarification

@rodolfomartinez FYI

**Comment by KPSbuttar** [comment]
Hi sir @bartmika finally this is COMPLETED all validations are simplified and manually created and as per latest html5 and bootstrap 4 standards. Form is updated as per correct standards, get method added. Old validation plugin script is not used because of conflict with latest version so i manually created ALL validations and updated jquery which will help in all FUTURE forms thats y taken so much time to finish this ticket.

So you can review new search corrected form here: http://inthought.pw/members/member_search.html
Test Basic search field validated to required and min 3 charecters. Then advanced search fields with concept AT LEAST any of the one field should be filled to get search results AND minimum first, last name char limit and VALID PHONE number validations all done.

Currently for advanced fields atleast any one validation ACTIVE if you want to make any of the fields in advanced search form compulsory simply add required because for this jquery "filed should not be blank" error message concept is done in jquery. 

Message me if any clarification or more functions to add.

ALL done 
Thanks

**Comment by KPSbuttar** [comment]
Hi sir @rodolfomartinez  this Big Concept is done it will help in all future forms validations are as Per Latest jQuery and Bootstrap 4 using HTML 5 (constraint validation API) and server defaults both type of validations added
