### ISSUE TITLE
Activate Logout

### ISSUE THREAD

**Issue by rodolfomartinez** [MikaSoftware/inthought#63]
**Summary:**
This may be a ticket for @bartmika - need to make logout active.

**Comment by bartmika** [comment]
I have I pleneted a successful logout code using Ajax. Maybe we could have a notification message at the login page which will say “you have successfully logged out”. @rodolfomartinez

**Comment by KPSbuttar** [comment]
@bartmika hi sir for this i will create notif at login page when user click logout button from side bar it will redirect to login page with logout message. But if possible can you show me Ajax code you created for logout function so i create jquery notif according to that. Thanks!

**Comment by bartmika** [comment]
1. https://github.com/over55/overfiftyfive-django/blob/master/overfiftyfive/shared_api/templates/shared_api/shared_api_js.html

2. https://github.com/over55/overfiftyfive-django/blob/master/overfiftyfive/shared_auth/urls.py#L46

**Comment by KPSbuttar** [comment]
Hi @rodolfomartinez @bartmika this is done. Please review here: http://inthought.pw/?logout=1
or  http://inthought.pw/?logout=success
So basically sir if logout happens you just need to pass a parameter named **logout** with values either **success** or **1** while 'logout/redirector' in django code url which redirects to login page.

And if parameter passed then "you have successfully log out" alert message appears otherwise when you visit login page normally you will see no such message. Backend jQuery is Done.
